#!/bin/bash

# This directory created using: virtualenv -p python3 .

source bin/activate

if ! which stomp; then
	pip install -i https://pypi.python.org/simple stomp.py
	pip install -r requirements.txt
	pip freeze > requirements.txt
fi

MOD_NAME=stompworker
#https://github.com/idlerun/simple-pex
createPex(){
 set -x
 echo "Build wheel to override Pex's cache"
 pip wheel -w ~/.pex/build/ .
 pex $MOD_NAME -f $PWD -r requirements.txt -m $MOD_NAME -o $MOD_NAME.pex
 set +x
}
